---

- name: Create folder structure
  file:
    path: "{{ docker_plex_base_dir }}/{{ item }}"
    state: directory
    mode: 0774
    owner: "{{ docker_plex_uid }}"
    group: "{{ docker_plex_gid }}"
    recurse: yes
  with_items:
    - data
    - config
    - transcode

- name: write docker-compose file
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_plex_base_dir }}/docker-compose.yml"

- name: control container
  docker_compose:
    project_src: "{{ docker_plex_base_dir }}"
